[package]
name = "isir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.11.0"
raw-window-handle = "0.3.3"

[dev-dependencies]
winit = "0.25.0"
pollster= "0.2"
